rust-vmm/mshv

.github/dependabot.yaml
.github/dependabot.yml

Removed the yaml configuration. All repos are using .yml instead.
Updated the existing configuration to open PRs weekly.

update dependabot config

---

mshv-bindings/src/regs.rs
mshv-ioctls/src/ioctls/vcpu.rs
mshv-ioctls/src/lib.rs

Clippy complains about a duplicate test attribute. It is in fact part
of a commented out test case.
requirements:
test.

Fix a few miscellaneous issues

---

mshv-bindings/src/bindings.rs

Ideally the whole file should be regenerated with Debug added to public
structs, but we will undergo some churns so do the minimum to solve our
immediate needs.
Signed-off-by: Wei Liu <liuwe@microsoft.com>
requirements:
test.

mshv-bindings: add Debug to mshv_user_mem_region

---

mshv-ioctls/src/ioctls/vcpu.rs

The index of the array should be adjusted.
requirements:
test.

mshv-ioctls: fix get_fpu

---

.gitignore

Add a gitignore to project and along with it add build and target directories to it,
requirements:
- [Done] All commits in this PR are signed (with `git commit -s`), and the commit
- [Done] All added/changed functionality has a corresponding unit/integration
test.
- [Done] Any newly added `unsafe` code is properly documented.

Add build and target directories to gitignore

---

.gitignore

requirements:
- [Done] All commits in this PR are signed (with `git commit -s`), and the commit
- [Done] All added/changed functionality has a corresponding unit/integration
test.
- [Done] Any newly added `unsafe` code is properly documented.

.gitignore: Add Cargo.lock file 

---

.github/workflows/quality.yaml
mshv-bindings/doc/generate-bindings.md
scripts/generate_binding.py

Adding a python script to automatically generate Rust bindings given a kernel source tree.
Fixes #36 
requirements:
- [Done] All commits in this PR are signed (with `git commit -s`), and the commit
- [Done] All added/changed functionality has a corresponding unit/integration
test.
- [Done] Any newly added `unsafe` code is properly documented.

scripts: Add a python script to generate Rust bindings

---

.buildkite/pipeline.yml
mshv-ioctls/src/ioctls/device.rs
mshv-ioctls/src/ioctls/vcpu.rs
mshv-ioctls/src/ioctls/vm.rs

Add buildkite build pipeline
Purpose:
- Configure pipeline to enable tests depend on /mshv driver
- Configure pipeline agent(buildkite)
- Custom test definitions 
requirements:
test.

Add buildkite build pipeline

---

.buildkite/pipeline.yml
coverage_config_x86_64.json

*Coverage test was missing in the pipeline configurations. This PR adds coverage test*
requirements:
test.

Add coverage test to the pipeline

---

CODEOWNERS

Add @jinankjain as the codeowner

---

mshv-ioctls/src/ioctls/vm.rs

Signed-off-by: Nuno Das Neves <nudasnev@microsoft.com>
Support resamplefd argument of mshv irqfd ioctl.
requirements:
test.

mshv-ioctls: Add register_irqfd_with_resample

---

mshv-ioctls/src/ioctls/vm.rs

need more work on MSHV to support resamplefd
Signed-off-by: Muminul Islam <muislam@microsoft.com>
requirements:
test.

Fix test_ioeventfd unit test

---

scripts/generate_binding.py

Two clean-up patches. No functional change.
requirements:
test.

Two clean-up patches

---

mshv-ioctls/src/ioctls/vcpu.rs

This especially concerns `subleaf_specific` and `ecx`. In cases like topology configuration that are passed through the leafs 0xb or 0x1f, multiple subleafs are involved and thus the hypercall arguments need to be prepared accordingly.
In addition to the exposed configuration parameters, some more inline documentation is added to improve the understanding on the hypercall configuration and arguments.

vcpu: Expose more parameters for register intercept result hypercall

---

mshv-ioctls/src/ioctls/vcpu.rs

This functionality was previously intended to be integrated on the Cloud Hypervisor side. According to the discussion in
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5325#discussion_r1156169782
the right place to have filtering and setting special options is however the mshv crate. This ensures this piece is
- Reusable from else where by including the mshv crate
- On the Cloud Hypervisor side, ensures the semantics is same as KVM
The [PR to Cloud Hypervisor ](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5325) is going to be modified accordingly once this change has landed in here.

cpuid: Implement special handling for some leaves

---

mshv-bindings/src/bindings.rs

Update the bindings using the latest MSHV header files.
requirements:
test.

mshv: Regenerate bindings using latest headers

---

mshv-ioctls/src/ioctls/vcpu.rs

Add VCPU API to set SEV control register
requirements:
test.

Add VCPU API to set SEV control register

---

mshv-bindings/Cargo.toml
mshv-ioctls/Cargo.toml

There is a recent CVE-2023-50711 assigned to this package and thus we should upgrade this package to the latest version.
requirements:
test.

mshv: Upgrade vmm-sys-utils to the latest version

---

.github/workflows/quality.yaml

- Update action/checkout from v2 to v4
- Update from action-rs/toolchain to dtolnay/rust-toolchain 
requirements:
test.

Update GithubCI to use latest stable action

---

mshv-bindings/src/bindings.rs

mshv-bindings: Add partition property for reference time

---

.github/workflows/clh_build.yaml

workflow: clone cloud-hypervisor repo as public
Do not use tokens.
requirements:
test.

workflow: clone cloud-hypervisor repo as public

---

.github/workflows/build.yaml

In the past, we have seen that there were failure while cross compiling the crate and due to which we broke pipeline of the dependent crates. Thus, add a cross compile build test for the crate to avoid such breakage in the future.
requirements:
test.

.github: Add a new workflow to cross compile and build

---

mshv-bindings/Cargo.toml
mshv-ioctls/Cargo.toml

Update Cargo.toml with new version number and tag a release.

release: v0.2.0

---

mshv-bindings/src/x86_64/snp.rs
mshv-ioctls/src/ioctls/mod.rs

Add definitions to handle GHCB page
requirements:
test.

Add definitions to handle GHCB page

---

mshv-bindings/Cargo.toml
mshv-ioctls/Cargo.toml

This metadata would be required while publishing the crate.
requirements:
test.

Cargo.toml: Update Cargo toml with metadata

---

mshv-bindings/Cargo.toml
mshv-ioctls/Cargo.toml

Update metadata description to comply with cargo publish standards.
requirements:
test.

Cargo.toml: Update metadata description to comply with cargo publish standards.

---

mshv-bindings/src/x86_64/snp.rs

mshv-bindings: implement send for svm_ghcb_base

---

mshv-bindings/src/hvcall.rs
mshv-ioctls/src/ioctls/system.rs
mshv-ioctls/src/ioctls/vm.rs

mshv-bindings: Fix rust clippy warnings

---

mshv-ioctls/src/ioctls/system.rs
mshv-ioctls/src/mshv_ioctls.rs

Along with it also add a unit test to verify if we can retrieve the host IPA properly.
requirements:
test.

mshv-ioctl: Add an interface to retrieve host partition property

---

.cargo/config.toml
.github/workflows/gitlint.yaml
.github/workflows/taplo.yaml
Cargo.toml
mshv-ioctls/Cargo.toml

Validate Cargo.toml and commit messages

---

CODEOWNERS

Add @praveen-pk as the codeowner. Having availability of more reviewers for faster PR processing.
requirements:
test.

Add @praveen-pk as the codeowner

---

mshv-bindings/CHANGELOG.md
mshv-bindings/Cargo.toml
mshv-ioctls/CHANGELOG.md
mshv-ioctls/Cargo.toml

Prepare for the new release of mshv crate to 0.3.3
requirements:
test.

Prepare for the new release of mshv crate

---

mshv-ioctls/src/ioctls/vcpu.rs

Use VP register page to get/set Special and extended registers

---

mshv-ioctls/src/ioctls/vcpu.rs

Validate VP register page before using it

---

mshv-bindings/CHANGELOG.md
mshv-bindings/Cargo.toml
mshv-ioctls/CHANGELOG.md
mshv-ioctls/Cargo.toml

Create a new release for mshv crates to v0.3.5
requirements:
test.

New release for mshv crate

---

.github/workflows/clh_build.yaml
scripts/use-local-mshv-for-clh-build.sh
scripts/use-local-mshv-for-vfio-build.sh
scripts/use-local-vfio-for-vfio-user-build.sh

Fix Cloud-Hypervisor and VFIO build workflow

---

mshv-ioctls/src/ioctls/system.rs

Rework Create Partition IOCTL

---

mshv-bindings/CHANGELOG.md
mshv-bindings/Cargo.toml
mshv-ioctls/CHANGELOG.md
mshv-ioctls/Cargo.toml

Preparing a new release of mshv crates. Since we have a breaking API change this time around, we are bumping the minor version to 0.5.0.
requirements:
test.

Release v0.5 for mshv crates

---

mshv-bindings/CHANGELOG.md
mshv-bindings/Cargo.toml
mshv-ioctls/CHANGELOG.md
mshv-ioctls/Cargo.toml
scripts/use-local-vfio-for-vfio-user-build.sh

Release v0.5.1 for mshv crates

---

mshv-ioctls/src/ioctls/system.rs

Without this we significantly increase the guest boot time with large number of vcpus.
requirements:
test.

mshv-ioctls: Advertize support for tsc invariance

---

mshv-bindings/CHANGELOG.md
mshv-bindings/Cargo.toml
mshv-ioctls/CHANGELOG.md
mshv-ioctls/Cargo.toml

Also, fix formatting in CHANGELOG

mshv: Update Cargo.toml and CHANGELOG for release.

---

.github/workflows/mshv-infra.yaml
.github/workflows/mshv-tests.yaml

This PR introduces two CI workflows to automate the testing of the mshv crate in a virtualized environment:
1. **VM Provisioning Workflow (Reusable)**  
- Provisions an Azure VM using managed identity  
- Sets VM name dynamically based on GitHub run ID  
- Prepares the environment for running tests
2. **Build and Test Workflow**  
- Triggers the provisioning workflow  
- Builds the mshv crate & runs unit tests via SSH on the provisioned remote VM

Add CI workflows to provision azure VM and run mshv unit tests

---

.github/workflows/clh_build.yaml
.github/workflows/vfio_build.yaml
scripts/use-local-mshv-for-clh-build.sh

Use defined tag for Cloud-Hypervisor and Vfio build

---

.github/dependabot.yml

ci: activate dependabot for github-actions

---

scripts/tag_release.py

This patch creates tags for both crates found in root Cargo.toml file. Not the user can call the script
without any argument to create both mshv-{ioctls, bindings} crates.
requirements:
test.

scripts: create all tags if crate is not specified
