- coverage_config_x86_64.json
- mshv-bindings/src/bindings.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
- mshv-ioctls/src/mshv_ioctls.rs
This PR updates the bindings that have the /dev/mshv API to retrieve the dirty page access states. There is also an API in MSHV crates to process the page states and convert them to a bitmap compatible with CLH live migration framework.
These are the last set of patches that were merged to cloud-hypervisor while the previous PR was pending. All the patches were cherry-picked from the Cloud Hypervisor project. After this PR both rust-vmm and CLH  repos are synced and we can move all the referent of these crates to rust-vmm.
> Add APIs to retrieve dirty page states

- coverage_config_x86_64.json
- mshv-bindings/src/bindings.rs
- mshv-ioctls/src/ioctls/device.rs
- mshv-ioctls/src/ioctls/mod.rs
- mshv-ioctls/src/ioctls/vm.rs
- mshv-ioctls/src/lib.rs
- mshv-ioctls/src/mshv_ioctls.rs
This is needed to support VFIO based passthrough.
Bindings are generated according to https://lore.kernel.org/linux-hyperv/20210709114339.3467637-1-wei.liu@kernel.org/.
> Add MSHV device fd bindings

- mshv-bindings/src/regs.rs
- mshv-ioctls/src/ioctls/device.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
These issues are detected with rustfmt's format_code_in_doc_comments.
Signed-off-by: Wei Liu <liuwe@microsoft.com>
> mshv: fix style issues in comments

- coverage_config_x86_64.json
- mshv-bindings/src/regs.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vcpu.rs
Enabled TLB flush and IPI synthetic features, added missing Hypercall register and GUEST_OS_ID MSR
> Enable more Synthetic features for guest performance

- mshv-bindings/src/bindings.rs
The two parts were in the wrong order.
Correct ordering is shown in https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/funcs/whvvirtualprocessordatatypes for WHV_UINT128 type.
requirements:
test.
> mshv-bindings: fix hv_u128

- mshv-bindings/src/hvdef.rs
- mshv-ioctls/src/ioctls/device.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
Signed-off-by: Muminul Islam <muislam@microsoft.com>
*Derive debug for public structs, This PR  does not derive debug for auto generated bindings since most of those struct has union fields. If needed we can add later while we generate new bindings*
requirements:
test.
> mshv-{bindings, ioctls}: derive debug for public struct

- mshv-bindings/src/bindings.rs
- mshv-ioctls/src/ioctls/vm.rs
MSHV allows changing the behavior for unimplemented MSRs. If the guest tries to access an unimplemented MSR default behavior is to send a fault to the guest. But this behavior can be overridden by setting the partition property called `UNIMPLEMENTED_MSR_ACTION`. With this PR support for changing this partition property is added, along with it a unit test to validate the behavior.
requirements:
- [Done] All commits in this PR are signed (with `git commit -s`), and the commit
- [Done] All added/changed functionality has a corresponding unit/integration
test.
- [Done] Any newly added `unsafe` code is properly documented.
> Add support for Unimplemented MSR action property

- mshv-bindings/src/regs.rs
- mshv-ioctls/src/ioctls/vcpu.rs
Currently we are assuming LDT register as a Table Register. Instead it
should be a segment register.
Reported-by: Dev Rajput <t-devrajput@microsoft.com>
requirements:
test.
> mshv: Make LDT register a segment register

- mshv-bindings/src/bindings.rs
- mshv-bindings/src/regs.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
With the new Microsoft Hypervisor binaries, the behavior for getting and
setting Lapic state has been changed. Now we need to provide an
additional buffer which is page aligned to get/set Lapic state from/to
Hypervisor.
While at it remove the useless get_lapic_ioctl() function since that is
not used by anyone. Also this function is bit redudant since we already
have get_lapic_state() and set_lapic_state() which achieves the same
functionality.
As part of this commit mshv-bindings are also updated to reflect the
change in LAPIC state type.
requirements:
test.
> mshv: Fix get/set for Lapic state

- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/lib.rs
Signed-off-by: Simon Davies <sdavies@microsoft.com>
#46 introduced `SyntheticProcessorFeature` and `MshvPartitionBuilder` that enables building a `mshv_create_partition` along with an API `create_vm_with_config` which accepts a parameter of type `mshv_create_partition`. That PR did not expose `SyntheticProcessorFeature` and `MshvPartitionBuilder`, this PR fixes that.
requirements:
test.
> Make SyntheticProcessorFeature and MshvPartitionBuilder pub

- coverage_config_x86_64.json
- mshv-bindings/src/lib.rs
- mshv-bindings/src/regs.rs
- scripts/generate_binding.py
The script has an additional parameter called `--bindgen` to pass
bindgen arguments transparently. You can use this new option in the
following way:
```sh
$ ./scripts/generate_binding.py --kernel ../linux-stable --log-level debug
--bindgen "--with-derive-eq --with-derive-ord"
DEBUG:root:Installing kernel headers at /tmp/linuxiwd2ds3d
DEBUG:root:Start generating unified header file
DEBUG:root:Done generating unified header file
DEBUG:root:Running bindgen:
bindgen --no-doc-comments --with-derive-default --no-derive-debug
--with-derive-eq --with-derive-ord --rustified-enum hv_register_name
/tmp/linuxiwd2ds3d/combined_mshv.h --
-I /tmp/linuxiwd2ds3d/include > mshv-bindings/src/bindings.rs
DEBUG:root:Cleaning up installed header files
```
Fixes #57
Signed-off-by: Jinank Jain …
> scripts: Add support for passing bindgen args

- mshv-ioctls/src/ioctls/vm.rs
... partition property. One of the partition property was moved to set of immutable partition property. One of the test was trying to mutate it and thus failing the tests. Instead refactor that test to make sure that we get an error if we try to change immutable partition property.
requirements:
test.
> mshv-ioctls: Add a new test to check immutable

- mshv-bindings/src/lib.rs
This should fix building the crate on aarch64.
Signed-off-by: Wei Liu <liuwe@microsoft.com>
See https://github.com/rust-vmm/vfio/pull/17
requirements:
test.
> mshv-bindings: import vmm_sys_util macros for all architectures

- .buildkite/pipeline.yml
VM type of the agent changed and the build takes loner than previous. Increasing the timeout to 10 minutes.
Signed-off-by: Muminul Islam <muislam@microsoft.com>
requirements:
test.
> buildkite: Increase timeout

- mshv-bindings/src/lib.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
Allow that for generated code and remove all unnecessary casts in other places.
Signed-off-by: Wei Liu <liuwe@microsoft.com>
The recent changes to bindings.rs changed some types from Rust enum to integer. That caused this issue.
It is surprising the previous CI run didn't catch this.
requirements:
test.
> bindings: fix clippy::unnecessary_cast warnings

- mshv-ioctls/src/ioctls/system.rs
Following two MSRs are disabled now since the
created partition is not using corresponding features.
1. IA32_MSR_BNDCFGS MSR can be accessed if any of the following features enabled HV_X64_PROCESSOR_FEATURE0_IBRS HV_X64_PROCESSOR_FEATURE0_STIBP HV_X64_PROCESSOR_FEATURE0_MDD HV_X64_PROCESSOR_FEATURE1_PSFD
2. IA32_MSR_SPEC_CTRL: MPX support needed for this MSR, currently feature is not enabled
Signed-off-by: Muminul Islam <muislam@microsoft.com>
requirements:
test.
> mshv-ioctls: Disable unused MSRs access

- mshv-bindings/src/bindings.rs
- mshv-ioctls/src/ioctls/system.rs
Recently we have changed the mshv create partition ioctl definition by moving out isolation property out of partition property. Thus, we should regenrate the bindings to reflect those changes and fix the API accordingly.
requirements:
test.
> mshv: Regenerate bindings to fix isolation props

- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/mshv_ioctls.rs
Add APIs for handling gpa_read/write hypercalls
requirements:
test.
> Add APIs for handling gpa_read/write hypercalls

- mshv-bindings/src/lib.rs
- mshv-bindings/src/snp.rs
Keep non-public MSHV definitions in the MSHV crate Most of this definitions are derived from AMD
specifications and are available in Hyper-V repo as well.
requirements:
test.
> Keep non-public Hyper-V  definitions in the MSHV crate

- mshv-ioctls/src/ioctls/vm.rs
- mshv-ioctls/src/mshv_ioctls.rs
- Ioctl for changing page visibility
- Ioctl for importing isolated pages
- Ioctl for completing isolated import
- Ioctl for creating AP threads for SEV-SNP guest
- Ioctl for issuing psp request from guest side.
requirements:
test.
> Add various ioctls required by SEV-SNP guest

- mshv-ioctls/src/ioctls/vcpu.rs
.... to include xfem and xss as input parameters. Those are required when we would be querying the extended cpuid topology leafs.
requirements:
test.
> mshv-ioctls: Extend get_cpuid_values interface

- mshv-bindings/src/snp.rs
Microsoft Hypervisor supports offloading some VMGEXITnon-atomic events to the hypervisor. VMM can utilize this feature by enabling VMG exit offloads. This patch adds a function that returns current supported features by MSHV.
requirements:
test.
> mshv-bindings: function to retrieve offloadble features

- mshv-ioctls/src/ioctls/vm.rs
- mshv-ioctls/src/lib.rs
VmType is needed by cloud hypervisor when trying to create a VM. Thus, we need to expose it to the public interface along with it also add support to convert u64 to VmType.
requirements:
test.
> Expose VmType to the public interface

- mshv-bindings/src/unmarshal.rs
Unmarshal hv_message to hv_x64_vmgexit_intercept_message
requirements:
test.
> mshv-bindings: Unmarshal hv_message to hv_x64_vmgexit_intercept_message

- mshv-bindings/src/unmarshal.rs
These new messages are sent by Microsoft Hypervisor in case of SEV-SNP VM running.
requirements:
test.
> Add support for unmarshalling new SEV-SNP message

- mshv-bindings/src/snp.rs
- Parsing GPA range
- Getting SEV control register
- Getting default SNP policy
requirements:
test.
> Add various helper function required by SEV-SNP guest

- mshv-ioctls/src/ioctls/vcpu.rs
This patch continues to expand on the CPUID handling. This patch adds more bits to handle the topology specific bits on AMD.
The handling is derived from the CPUID Specification to involde the AMD specific leafs to configure the topology. The corresponding information is passed from the VMM.
Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>
> cpuid: Add bits to support AMD specific topology handling

- mshv-bindings/Cargo.toml
- mshv-bindings/src/bindings.rs
- mshv-bindings/src/hvdef.rs
- mshv-bindings/src/lib.rs
- mshv-bindings/src/regs.rs
With new version of zerocopy there are multiple breaking changes that would need fixing on mshv-bindings side.
This PR is a super set of #112 
requirements:
test.
> Fix issues with new version of zerocopy

- mshv-ioctls/src/ioctls/vcpu.rs
These leafs are relevant for topology, multithreading and other aspects of topology configuration. See AMD Architecture Programmers Manual (Publication #40332) for the single leafs details.
These leafs are relevant for topology, multithreading and other aspects of topology configuration. See AMD Architecture Programmers Manual (Publication #40332) for the single leafs details. Ref 
https://www.amd.com/content/dam/amd/en/documents/processor-tech-docs/programmer-references/40332.pdf
> cpuid: Handle more AMD specific topology leafs

- mshv-bindings/src/lib.rs
incorrect_clone_impl_on_copy_type is changed to non_canonical_clone_impl. Thus, rename it.
requirements:
test.
> mshv-bindings: Rename clippy warning

- mshv-bindings/src/regs.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/mshv_ioctls.rs
- `MSHV_CHECK_EXTENSION` will soon be replaced, so remove it here ahead of time. The associated function `check_stable()` is not used in any case.
- An upcoming PR uses `__IncompleteArrayField` and I was getting a compiler warning about it being defined twice - it should only be defined in `bindings.rs` AFAIK.
> Clean up unused MSHV_CHECK_EXTENSION and re-defined __IncompleteArrayField

- mshv-ioctls/src/ioctls/system.rs
Enable direct mode for synthetic timers. This allows synthetic timer interrupts to work early in the boot without having to wait for VMbus to be initialized.
> mshv-ioctls/system: Enable Direct mode stimer

- mshv-ioctls/src/ioctls/system.rs
This is needed to influence guest Linux to use physical address mode for MSIs (which it does by default when x2apic is enabled), which allows to support virtual interrupt injections in MSHV driver and thus improve overall VirtIO throughput.
requirements:
test.
> Enable x2apic for regular guests

- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/lib.rs
Remove conditional compilation for x86_64.
requirements:
test.
> mshv-ioctls: Add support for aarch64

- mshv-ioctls/src/lib.rs
- mshv-ioctls/src/mshv_ioctls.rs
In Cloud Hypervisor, the seccomp rules have hardcoded IOCTL numbers from the various bindings crates.
It would be nice to just get the IOCTL numbers from the crate itself. At the very least, it saves the time of having to compute or print out the IOCTL numbers manually when changing them or adding new ones.
Also add the MSHV_GET_VERSION_INFO IOCTL number.
requirements:
test.
> Export ioctl numbers

- mshv-bindings/src/regs.rs
- mshv-bindings/src/serializers.rs
- mshv-ioctls/src/ioctls/vcpu.rs
*This PR adds necessary structs, APIs, unit tests to save and restore synthetic state components *
requirements:
test.
> Add necessary APIs to interact with synthetic state components

- mshv-bindings/src/regs.rs
Constants like LAPIC_STATE size could be derived by calling size_of on the struct LapicState. In the similar fashion, other values can also be derived. Use a const function to intialize the various component sizes.
requirements:
test.
> mshv-bindings: Derive constant instead of hard-coding

- mshv-bindings/src/hvcall.rs
- mshv-bindings/src/lib.rs
- mshv-ioctls/src/ioctls/mod.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
- mshv-ioctls/src/mshv_ioctls.rs
This PR introduces the generic hypercall IOCTL - MSHV_ROOT_HVCALL.
It can be used on both the partition and vp fds.
This IOCTL reduces the number of IOCTLs needed in the kernel interface, reducing maintenance and making the kernel code more upstreamable.
This PR introduces the IOCTL and implements some use-cases for it, but it doesn't replace the default implementations so it won't affect downstream.
requirements:
test.
> Introduce generic hypercall ioctl

- mshv-bindings/src/hvcall.rs
To reduce namespace pollution and avoid a conflict with vec_with_array_field in cloud hypervisor.
requirements:
- [ x ] All commits in this PR have Signed-Off-By trailers (with
- [ x ] All added/changed functionality has a corresponding unit/integration
test.
- [ x ] All added/changed public-facing functionality has entries in the "Upcoming 
- [ x ] Any newly added `unsafe` code is properly documented.
> bindings: Move hvcall:: functions into impl scopes

- .github/workflows/clh_build.yaml
- scripts/use-local-mshv.sh
> Build Cloud-hypervisor on every PR

- mshv-bindings/src/hvcall.rs
- mshv-bindings/src/x86_64/regs.rs
- mshv-bindings/src/x86_64/serializers.rs
- mshv-bindings/src/x86_64/unmarshal.rs
- mshv-ioctls/src/ioctls/mod.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
Adding line breaks through out the project after each functions and definitions.
requirements:
test.
> mshv-{bindings, ioctls}: add line breaks

- mshv-bindings/src/arm64/bindings.rs
- mshv-bindings/src/x86_64/bindings.rs
- scripts/generate_binding.py
> Generate new bindings

- mshv-ioctls/src/ioctls/vm.rs
Users of mshv-ioctls-0.2.x can experience heap corruption when using dirty page tracking, and need this patch to avoid this.
requirements:
test.
> get_gpa_access_state: avoid returning dangling reference

- mshv-ioctls/src/ioctls/vcpu.rs
Add a new test case to test the vp_run method that uses mapped registers page and hv_message page.
requirements:
test.
> mshv-ioctls: test case to validate map VP state page

- mshv-bindings/Cargo.toml
- mshv-bindings/src/hvdef.rs
- mshv-bindings/src/x86_64/regs.rs
Change the usage of zerocopy to adapt to the latest version.
requirements:
test.
> Bump zerocopy crate to the lastest version

- mshv-bindings/CHANGELOG.md
- mshv-bindings/Cargo.toml
- mshv-ioctls/CHANGELOG.md
- mshv-ioctls/Cargo.toml
Update Cargo.toml with new version number. Release is needed to update CLH with CVM changes
requirements:
test.
> release: v0.3.1

- mshv-bindings/src/x86_64/snp.rs
Tree Borrows is a proposed replacement for Stacked Borrows, which is more permissive in general, but introduces new UB in edge cases. This commit fixes one such edge case.
[Tree Borrows](https://www.ralfj.de/blog/2023/06/02/tree-borrows.html) is a proposed replacement for Stacked Borrows, or at least an alternative aliasing model. It tries to fix some of Stacked Borrows shortcomings, and is in general more relaxed. There are however some areas where it has more UB than Stacked Borrows, and this crate seems to exhibit one of these examples. The fix is very small, and the problem arose because the code unnecessarily created a reference where none should have been created.
I did however not read the entire code to find if this is the only place this pattern occurs in; though it is the only …
> Make test suite pass under Tree Borrows

- mshv-bindings/CHANGELOG.md
- mshv-bindings/Cargo.toml
- mshv-ioctls/CHANGELOG.md
- mshv-ioctls/Cargo.toml
We are in the process of releasing a new minor version of mshv crates.
requirements:
test.
> mshv: Update changelog to prepare for new release

- mshv-ioctls/src/ioctls/vcpu.rs
Some of these unit tests are targeted for x86 architecture, thus conditionally compile them on x86.
requirements:
test.
> Make tests conditionally compile for x86

- mshv-bindings/src/lib.rs
- mshv-bindings/src/x86_64/regs.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
> Update get/set Standard Registers to use VP register page

- mshv-bindings/src/arm64/mod.rs
- mshv-bindings/src/arm64/unmarshal.rs
.... message. This would be used to be CLH while handling VMEXITs for ARM64 guests.
requirements:
test.
> mshv-bindings: Add support for unmarshaling memory intercept

- mshv-ioctls/src/ioctls/vcpu.rs
Get/Set reg interface works the same way on ARM64 as it works on x86. So there is no point of conditional compilation on just x86 architecture.
requirements:
test.
> mshv-ioctls: Implement get/set reg for aarch64

- scripts/use-local-mshv-for-clh-build.sh
- scripts/use-local-mshv-for-vfio-build.sh
- scripts/use-local-vfio-for-vfio-user-build.sh
In upstream VFIO crates there is a a chnage in the path of vfio-{bindings, ioctls} crate. This fixes the path for a successful CI run.
requirements:
test.
> scripts: fix vfio crate path

- mshv-bindings/src/arm64/bindings.rs
- mshv-bindings/src/x86_64/bindings.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vm.rs
- mshv-ioctls/src/mshv_ioctls.rs
Fix get_host_partition_property to return unsigned 64 bits property value.
requirements:
test.
> mshv-ioctls: property value is 64 bits

- mshv-ioctls/src/ioctls/system.rs
Instead, we should let VMM decide when it wants to initialize the partition. For example, for an ARM64 guest VMM needs to setup GIC params before the partition is initialized. Because the GIC params are early partition properties which can only be set before the partition is initialized.
In general, since MSHV considers a distinction between partition creation vs partition initialization, we should reflect the same in our APIs and not club together into a single function.
requirements:
test.
> mshv-ioctls: Don't initialize partition after creation

- mshv-bindings/src/x86_64/regs.rs
- mshv-ioctls/src/ioctls/vcpu.rs
If fast interrupt is used, interrupt vectors from register
page need to be saved and restored.
requirements:
test.
> mshv-{bindings, ioctls): save and restore interrupt vectors

- mshv-ioctls/src/ioctls/system.rs
ARM64 always require GICV3V4 processor feature is enabled for the guests. Otherwise MSHV would fail the creation of partition.
requirements:
test.
> mshv-ioctls: Fix ARM64 guest default processor feature set

- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
Retain the original interfaces and IOCTL definition to keep compatibility with the VMM code for now.
> ioctls: use new hvcall_ versions for ioctls

- mshv-ioctls/src/ioctls/device.rs
- mshv-ioctls/src/ioctls/system.rs
- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
It was removed from create_vm_with_type(), breaking the tests.
> ioctls: Add vm.initialize() to tests

- mshv-ioctls/src/ioctls/vcpu.rs
We were using the incorrect mask to obtain the translated address from the hypercall.
requirements:
test.
> mshv-ioctls: Fix a bug in translate gva hypercall

- mshv-ioctls/src/ioctls/vcpu.rs
- mshv-ioctls/src/ioctls/vm.rs
`ROOT_HVCALL` and `MSHV_CREATE_DEVICE` ioctl invocation should use `ioctl_with_mut_ref` to receive data from the kernel
requirements:
test.
> Fix ioctl invocations

- mshv-ioctls/src/ioctls/mod.rs
- mshv-ioctls/src/ioctls/system.rs
- scripts/use-local-mshv-for-vfio-build.sh
Downgrade the versions of kvm-bindings, kvm-ioctls and vmm-sys-util until the newer versions are picked up by cloud-hypervisor upstream.
requirements:
test.
> scripts: temp fix to unblock the CI

- mshv-bindings/Cargo.toml
- mshv-ioctls/Cargo.toml
Since other rust-vmm crates have already bumped this crate we should do the same.
requirements:
test.
> build: Bump vmm-sys-util from v0.12.1 to v0.14.0

- scripts/use-local-mshv-for-vfio-build.sh
This reverts commit 2d14df227258ec3886143ce88366de0f6f6aa685, since cloud hypervisor kvm versions are up to date with vfio now.
> Revert "scripts: temp fix to unblock the CI"

- hv-headers/hvgdk_mini.h
- hv-headers/hvhdk.h
- hv-headers/hvhdk_mini.h
- mshv-bindings/src/arm64/bindings.rs
- mshv-bindings/src/hvcall.rs
- mshv-bindings/src/x86_64/bindings.rs
- mshv-ioctls/src/ioctls/system.rs
Use the passthrough hvcall IOCTL on the /dev/mshv fd to perform a self query for VMM capabilities.
requirements:
test.
> mshv: add function to query vmm capabilities

- mshv-ioctls/CHANGELOG.md
- mshv-ioctls/src/ioctls/system.rs
This is needed specifically for SEV-SNP guests. Without this CVM guests don't boot.
requirements:
test.
> mshv-ioctls: enable RDRAND support for x86 guests

- mshv-ioctls/CHANGELOG.md
- mshv-ioctls/src/ioctls/system.rs
Expose PMU to arm64 guests. Fixes the test_pmu_on testcase in CLH.
requirements:
test.
> mshv-ioctls: enable PMU for arm64 guests

- mshv-ioctls/src/ioctls/vcpu.rs
Make sure that the register page is unmapped when the vcpu object is dropped Add tests to ensure that resources are not leaked
#194 details a regression that was found moving from version 0.3.2 to version 0.3.3 of the mshv crates, this was caused by the changes in #183 that mmap the register page on creation of a vcpu not having a corresponding munmap when the vcpu is dropped resulting in resource not being freed.
The PR adds a drop impl to conditionally unmap the register page
requirements:
test.
> mshv:ioctls munmap register page

- README.md
Providing the explicit commands in one place makes it even easier to do all the steps for a release.
> docs: Document commands to publish to crates.io

- .github/workflows/gitlint.yaml
Sometimes PR created by dependabot might not meet the requirement of commit message due to dependent
package with long name and some other information. It's better to avoid commit message validation for such  PRs.
requirements:
test.
> .github: skip commit message validation for PRs by bot
